### ISSUE TITLE
About your Video2Gif API

### ISSUE THREAD

**Issue by inglesuniversal** [jolav/codetabs#4]
Can I get a 5 to 10 sec gif from a video and make it a thumbnail like on youtube?

If that is the case, can the file be larger and restrict the output size prior to upload or through api?

I have a website with a bunch of videos, but they all have boring plain video camera icons

Any ideas?

Regards

**Comment by jolav** [comment]
> Can I get a 5 to 10 sec gif from a video and make it a thumbnail like on youtube?

I thought that a thumbnail was a single image although I do not see any problem in using a animated gif as a thumbnail.

You can set => frames 1, start X ,duration 1.  You will get a gif with only one frame in order to use it as a thumbnail 

> If that is the case, can the file be larger and restrict the output size prior to upload or through api?

Right now API needs the full video uploaded.  
I must investigate about a workaround for this

> I have a website with a bunch of videos, but they all have boring plain video camera icons
> Any ideas?

It depends.  
Video formats ? quantity ? average size per video ?  
If you are talking about TBs of data i think your better option is running a script to create thumbails from video using ffmpeg  
[Create a thumbnail image every X seconds of the video](https://trac.ffmpeg.org/wiki/Create%20a%20thumbnail%20image%20every%20X%20seconds%20of%20the%20video)

Thanks for your feedback. I had not noticed about thumbnails but now i will work on it.
Regards
